Robert-Sheehy/Worms-3D-Games-Dev-2018

Documents/Dean Kennelly work flow.txt
=> Created personal work flow file

Documents/IanOReganWorkFlow.txt
=> Created Personal Work Flow file. Professional Message

Documents/Daragh_Carroll_Workflow.txt
=> Created personal workflow file - First Commit

Documents/ModestasCepulisWorkFlow.txt
first commit :D hello thank you
=> Created personal .txt work flow file :D please accept

Worms 3D/Assets/Prefabs/FruitGrenadePrefab.prefab, Worms 3D/Assets/Prefabs/MissilePrefab.prefab, Worms 3D/Assets/Prefabs/MissilePrefab.prefab.meta, Worms 3D/Assets/ProjectileControl.cs, Worms 3D/Assets/ProjectileSpawner.cs, Worms 3D/Assets/Projectiles Scenes/Projectile Test.unity, Worms 3D/ProjectSettings/ProjectVersion.txt
Signed-off-by: Ryan Madigan <t00200799@365s.ittralee.ie>
=> Worked with projectiles and spawner, got scripts communicating

Worms 3D/Assets/Health.cs, Worms 3D/Assets/Health.cs.meta, Worms 3D/Assets/HealthTest.unity, Worms 3D/Assets/HealthTest.unity.meta, Worms 3D/Assets/PickUpItemTest.unity, Worms 3D/Assets/PickUpItemTest.unity.meta, Worms 3D/Assets/healthDriverTest.cs, Worms 3D/Assets/healthDriverTest.cs.meta, Worms 3D/ProjectSettings/TagManager.asset
Signed-off-by: Ryan Madigan <t00200799@365s.ittralee.ie>
=> Worked on Health and health driver script

Worms 3D/Assets/FloatingDisplay.cs, Worms 3D/Assets/Health.cs, Worms 3D/Assets/HealthandFloatingText.unity, Worms 3D/Assets/HealthandFloatingText.unity.meta, Worms 3D/Assets/WormMovementScenes/WormControl.cs
Worked on by: Ryan Madigan, Liam Dowling, Ryan Cosheril, Dean
Kennelly, Jack Gammon, Evan Barry
Display the health over the worm.
=> Signed-off-by: Ryan Madigan <t00200799@365s.ittralee.ie>

Worms 3D/Assets/FloatingDisplay.cs, Worms 3D/Assets/PlayerControl.cs, Worms 3D/Assets/PlayerControl.cs.meta, Worms 3D/Assets/PlayerControllerTest.unity, Worms 3D/Assets/PlayerControllerTest.unity.meta, Worms 3D/Assets/ProjectileSpawner.cs, Worms 3D/Assets/WormMovementScenes/WormControl.cs
Added "PlayerControl" which switches between active worms
=> Signed-off-by: Daragh K. Carroll <t00201097@365s.ittralee.ie>

Worms 3D/Assets/FloatingDisplayTest.unity, Worms 3D/Assets/Projectile.prefab, Worms 3D/Assets/ProjectileControl.cs, Worms 3D/Assets/ProjectileSpawner.cs, Worms 3D/Assets/TimeAndDisplayCountup.cs, Worms 3D/Assets/WormMovementScenes/WormControl.cs, Worms 3D/ProjectSettings/TagManager.asset
Signed-off-by: Ryan Madigan <t00200799@365s.ittralee.ie>
=> Worked on grenade timer and AOE effect

Worms 3D/Assets/FloatingDisplay.cs, Worms 3D/Assets/Health.cs, Worms 3D/Assets/PlayerControl.cs, Worms 3D/Assets/WormMovementScenes/WormControl.cs
+ Floating display changes color depending on which worm is selected by PlayerController
+ team1 list initialized and populated with instanciated worms
+ Added several of irrelevant comments
Signed-off-by: Liam Dowling <t00199360@365s.ittralee.ie>
+ DC(t00201097), MC(t00199237), IoR, EF, RC.
=> Changelog 10/10/2018

Worms 3D/Assets/Health.cs, Worms 3D/Assets/Prefabs/FruitGrenadePrefab.prefab, Worms 3D/Assets/ProjectileControl.cs, Worms 3D/Assets/ProjectileSpawner.cs, Worms 3D/Assets/Projectiles Scenes/Projectile Test.unity, Worms 3D/Assets/WormMovementScenes/WormControl.cs, Worms 3D/ProjectSettings/TagManager.asset
Signed-off-by: Ryan Madigan <t00200799@365s.ittralee.ie>
=> Grenade Explosions continued, bug fixing..

Worms 3D/Assets/AimCameraControl.cs, Worms 3D/Assets/AimCameraControl.cs.meta, Worms 3D/Assets/Prefabs/FruitGrenadePrefab.prefab, Worms 3D/Assets/ProjectileSpawner.cs, Worms 3D/Assets/Projectiles Scenes/Projectile Test.unity, Worms 3D/ProjectSettings/InputManager.asset, Worms 3D/ProjectSettings/ProjectVersion.txt
Signed-off-by: Ryan Madigan <Ryan.Madigan@students.ittralee.ie>
=> Worked on aiming with camera and firing with mouse

Worms 3D/Assets/Health.cs, Worms 3D/Assets/PlayerControl.cs, Worms 3D/Assets/WormMovementScenes/WormControl.cs
Signed-off-by: Daragh K. Carroll <Daragh.K.Carroll@students.ittralee.ie>
=> Started work on teams

Worms 3D/Assets/Health.cs, Worms 3D/Assets/PlayerControl.cs, Worms 3D/Assets/Team.cs, Worms 3D/Assets/WormMovementScenes/WormControl.cs
Death control has been handed to WormControl and PlayerControl but not yet implemented
Large changes made to Health, PlayerControl, WormControl and Team Scripts
Signed-off-by: Ian O Regan <Ian.ORegan@students.ittralee.ie>
=> Player Control can now iterate through each team and worm in turn.

Worms 3D/Assets/Health.cs, Worms 3D/Assets/PlayerControl.cs, Worms 3D/Assets/ProjectileSpawner.cs, Worms 3D/Assets/WormMovementScenes/WormControl.cs, Worms 3D/Assets/grenadeDisplayFixTest.unity, Worms 3D/Assets/grenadeDisplayFixTest.unity.meta, Worms 3D/Assets/grenadeDisplayTestFix.cs, Worms 3D/Assets/grenadeDisplayTestFix.cs.meta
ALL THE CODE I DID IS COMMENTED OUT SO IF IT DOESNT WORK ITS NOT MY FAULT
=> Signed-off-by: Liam Dowling <Liam.Dowling@students.ittralee.ie>

Worms 3D/Assets/Inventory.cs, Worms 3D/Assets/Inventory.cs.meta, Worms 3D/Assets/PlayerControl.cs, Worms 3D/Assets/Team.cs
Signed-off-by: Daragh K. Carroll <Daragh.K.Carroll@students.ittralee.ie>
=> Added Inventory class and modified Teams class to include inventory systems

Worms 3D/Assets/Health.cs, Worms 3D/Assets/PlayerControl.cs, Worms 3D/Assets/Prefabs/WallPrefab.prefab, Worms 3D/Assets/Prefabs/WallPrefab.prefab.meta, Worms 3D/Assets/Projectiles Scenes/Projectile Test.unity, Worms 3D/Assets/WallTest.cs, Worms 3D/Assets/WallTest.cs.meta, Worms 3D/Assets/WallTest.unity, Worms 3D/Assets/WallTest.unity.meta, Worms 3D/Assets/wall.cs, Worms 3D/Assets/wall.cs.meta, Worms 3D/ProjectSettings/TagManager.asset
Created wall and wallTest script to set wall health and if it is destructable or not
=> Signed-off-by: Ryan Madigan <Ryan.Madigan@students.ittralee.ie>

Worms 3D/Assets/GameManager.cs, Worms 3D/Assets/GameManager.cs.meta, Worms 3D/Assets/GameManagerTest.unity, Worms 3D/Assets/GameManagerTest.unity.meta, Worms 3D/Assets/Prefabs/Plane.prefab, Worms 3D/Assets/Prefabs/Plane.prefab.meta, Worms 3D/Assets/Prefabs/SurroundingWallFrontBack.prefab, Worms 3D/Assets/Prefabs/SurroundingWallFrontBack.prefab.meta
GameManager script for now will instantiate the ground and surrounding walls
Signed-off-by: Evan Barry <Evan.Barry@students.ittralee.ie>
=> Created GameManager script and GameManagerTest scene

Worms 3D/Assets/Health.cs, Worms 3D/Assets/Team.cs, Worms 3D/Assets/WormMovementScenes/WormControl.cs, Worms 3D/ProjectSettings/ProjectVersion.txt, Worms 3D/UnityPackageManager/manifest.json
Signed-off-by: Ian O Regan <Ian.ORegan@students.ittralee.ie>
=> Minor tweaks

Worms 3D/Assets/FloatingDisplay.cs, Worms 3D/Assets/Health.cs, Worms 3D/Assets/ProjectileSpawner.cs, Worms 3D/Assets/WormMovementScenes/WormControl.cs, Worms 3D/Assets/grenadeDisplayTestFix.cs, Worms 3D/UnityPackageManager/manifest.json
Signed-off-by: Liam Dowling <Liam.Dowling@students.ittralee.ie>
=> fixed the grenade display

Worms 3D/Assets/GameManager.cs, Worms 3D/Assets/GameManagerTest.unity, Worms 3D/Assets/Prefabs/WallPrefab.prefab, Worms 3D/Assets/Prefabs/platform.prefab, Worms 3D/Assets/Prefabs/platform.prefab.meta, Worms 3D/Assets/wall.cs, Worms 3D/ProjectSettings/ProjectVersion.txt, Worms 3D/UnityPackageManager/manifest.json
Made spawnWalls method
Signed-off-by: Evan Barry <Evan.Barry@students.ittralee.ie>
=> Input wall prefeb into gameManager scene

Worms 3D/Assets/WormMovementScenes/WormControl.cs, Worms 3D/Assets/healthDriverTest.cs
Signed-off-by: Ian O Regan <Ian.ORegan@students.ittralee.ie>
=> Added some parameters and a ray cast of usage in the jump function

Worms 3D/Assets/PlayerControllerTest.unity, Worms 3D/Assets/Score/ScoreAndTimerScene.unity, Worms 3D/Assets/Score/Scripts/ScoreScript.cs
Signed-off-by: Emma P. Fitzgerald <Emma.P.Fitzgerald@students.ittralee.ie>
=> Fixed the timer and score
